# -*- coding: utf-8 -*-
"""Nodes per hidden layer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DYhgov-s2niUtYqDijpTtXfIjw37gNg9
"""

import numpy as np

def compute_nb_nodes_per_h_layer(n_param, h, insz, outsz):
  a = h - 1
  b = insz + outsz + h
  c = outsz - n_param

  x1 = (-b + np.sqrt(b**2 - 4*a*c))/(2*a)
  # x2 = (-b - np.sqrt(b**2 - 4*a*c))/(2*a)
  return x1

print('CIFAR-10')
print(compute_nb_nodes_per_h_layer(1117866, 3, 32*32*3, 10))
print('CIFAR-10 Gray')
print(compute_nb_nodes_per_h_layer(1117290, 3, 32*32*1, 10))
print('MNIST')
print(compute_nb_nodes_per_h_layer(871530, 3, 28*28, 10))